var transLang={"ru":{"Lang":"ru",
					"headTitle":"Простой список задач на день",
					"menuHelp":"Помощь",
					"HelpBody":"<p>Тут будет Help<p>Этот на русском",
					"helpDivLabel":"Помощь",
					"Title":"Простой список задач на день",
					"SkipLink":"Пропустить задачу",
					"menuSetup":"Настройка",
					"setupDivLabel":"Настройка",
					"cancelSetupButton":"Отмена",
					"Done":"Все сделано, можно идти домой",
					"cancelHelpButton":"Закрыть",
					"saveSetupButton":"Записать"},
			  "en":{"Lang":"",
			  		"headTitle":"Simple todo list for one day",
			  		"menuHelp":"Help",
			  		"HelpBody":"<p>This is a a help<p>English version",
			  		"helpDivLabel":"Help",
			  		"Title":"Simple todo list for one day",
			  		"SkipLink":"Skip task",
					"menuSetup":"Setup",
					"setupDivLabel":"Setup",
					"cancelSetupButton":"Cancel",
					"Done":"All done, you can go to home",
					"cancelHelpButton":"Close",
					"saveSetupButton":"Save"}
}				


// var en={"Lang":"",
//		"headTitle":"",
//		"menuHelp":"",
//		"HelpBody":"",
//		"helpDivLabel":"",
//		"Title":"",
//		"SkipLink":"",
// 		"menuSetup":"",
// 		"setupDivLabel":"",
// 		"cancelSetupButton":"",
//		"Done":"",
//		"cancelHelpButton":"",
// 		"saveSetupButton":""};		